using Meishi.Server.Services.GithubAuth.Models;

namespace Meishi.Server.Services.GithubAuth
{
    public interface IGithubAuthService
    {
        /// <summary>
        ///     Sends a request to the GitHub API to get the user's access token
        /// </summary>
        /// <param name="code"> Code received from the authorization request </param>
        /// <returns>The access token generated by GitHub</returns>
        Task<GithubAccessTokenResponse> GetAccessTokenAsync(string code);

        /// <summary>
        ///     Sends a request to the GitHub API to refresh the user's access token
        /// </summary>
        /// <param name="refreshToken"> The refresh token received when the access token was first generated</param>
        /// <returns>The new access token generated by GitHub</returns>
        Task<GithubAccessTokenResponse> RefreshTokenAsync(string refreshToken);
    }
}
